### PR TITLE
Nest relationships under 'data' key and preserve relationship links under 'links'

### PR DESCRIPTION
**Pull request by liukaren**
This prevents paging links (next, prev) from being discarded.

@jede I'm having an issue parsing links that are nested under a relationship. This might not be the best way of doing it (it would certainly break existing clients) so let me know if you have ideas about how it should be done! The issue can be seen in the 'should handle relations with links' test.

Thanks for your time!

cc @AprilArcus @21echoes

### CODE REVIEW

**Comment by jede** [comment]
Hi!

Thanks for this! Really interesting! There is the issue with compatibility as you say. I kind of like that you can access the attributes directly on your model... I'm thinking lets keep the links mehtod and then add a  get('attr') method to the objects so that if you have an attribute named 'links' you could just access it by calling model.get('links'), but for other attributes you still can call model.name. What do you think?

**Comment by liukaren** [comment]
That sounds great! Is this closer to what you had in mind?

**Comment by jede** [comment]
Great! Thanks for this! I'll implement the new get method and make a release.

**Comment by jede** [comment]
This was released in yayson@2.0.0-beta.5! Thanks again!

**Comment by liukaren** [comment]
Yay! :) Thank you!

**Pull request merged**
